apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-dev-env
  template:
    metadata:
      labels:
        app: python-dev-env
    spec:
      containers:
      - name: python-dev-env
        image: eliottbonte/python-dev-env:latest
        ports:
        - containerPort: 8888
